version: "3.9"

services:
  db:
    image: postgres:13
    ports:
      - "5432:5432"
    volumes:
      - sailpgsql:/var/lib/postgresql/data
    env_file: mozart/conf/.env
    networks:
      - sail
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: ["./docker/wait-for-db.sh", "db", "./mozart/manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - .:/code
    ports:
      - "80:8000"
    env_file: mozart/conf/.env
    networks:
      - sail
    depends_on:
      - db
networks:
  sail:
    driver: bridge
volumes:
    sailpgsql:
        driver: local